# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myloginsystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 463)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -30, 861, 511))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.label.setStyleSheet("\n"
"\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/backgroundimage/scenery.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(120, 30, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("color: rgb(255, 255, 255)")
        self.login.setAlignment(QtCore.Qt.AlignCenter)
        self.login.setObjectName("login")
        self.usernamelabel = QtWidgets.QLabel(self.centralwidget)
        self.usernamelabel.setGeometry(QtCore.QRect(50, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.usernamelabel.setFont(font)
        self.usernamelabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.usernamelabel.setObjectName("usernamelabel")
        self.passwordlabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordlabel.setGeometry(QtCore.QRect(50, 220, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.passwordlabel.setFont(font)
        self.passwordlabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.passwordlabel.setObjectName("passwordlabel")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 150, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setStyleSheet("border-radius: 20px")
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setFrame(True)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 250, 391, 41))
        self.lineEdit_2.setStyleSheet("border-radius: 20px")
        self.lineEdit_2.setMaxLength(16)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.loginbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loginbutton.setGeometry(QtCore.QRect(180, 310, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("QPushButton {\n"
"  \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"\n"
"\n"
"   ")
        self.loginbutton.setObjectName("loginbutton")
        self.msglabel = QtWidgets.QLabel(self.centralwidget)
        self.msglabel.setGeometry(QtCore.QRect(50, 400, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.msglabel.setFont(font)
        self.msglabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.msglabel.setObjectName("msglabel")
        self.clickmebutton = QtWidgets.QPushButton(self.centralwidget)
        self.clickmebutton.setGeometry(QtCore.QRect(340, 400, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clickmebutton.setFont(font)
        self.clickmebutton.setStyleSheet("QPushButton {\n"
"  \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.clickmebutton.setObjectName("clickmebutton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log-In"))
        self.login.setText(_translate("MainWindow", "Log-In"))
        self.usernamelabel.setText(_translate("MainWindow", "Username:"))
        self.passwordlabel.setText(_translate("MainWindow", "Password:"))
        self.lineEdit.setWhatsThis(_translate("MainWindow", "Enter the username of the user"))
        self.lineEdit_2.setWhatsThis(_translate("MainWindow", "Enter the password of the user"))
        self.loginbutton.setText(_translate("MainWindow", "Log-In"))
        self.msglabel.setText(_translate("MainWindow", "Forgot your password?"))
        self.clickmebutton.setText(_translate("MainWindow", "Click me"))
import backgroundimage_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
